# This is a basic workflow that is manually triggered

name: Package Releases

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: get-framework
      uses: robinraju/release-downloader@v1
      with:
        latest: true
        repository: paulov-t/Paulov.Bepinex.Framework
        fileName: 'Paulov.Bepinex.Framework.zip'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: get-minimal
      uses: robinraju/release-downloader@v1
      with:
        latest: true
        repository: paulov-t/Paulov.Tarkov.Minimal
        fileName: '*v*.zip'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: get-local
      uses: robinraju/release-downloader@v1
      with:
        latest: true
        repository: paulov-t/Paulov.Tarkov.Local
        fileName: '*v*.zip'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: package-files
      shell: pwsh
      run: |
        Compress-Archive -Path "./" -DestinationPath Paulov.Tarkov.Package.zip

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
          draft: true
          prerelease: true
          files: Paulov.Tarkov.Package.zip
          token: ${{ secrets.PAT_KEY }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
    
